### ISSUE TITLE
Uppercase file extensions when launched with image

### ISSUE THREAD

**Issue by floofcheeks** [torcado194/opti#1]
When launching opti with a file supplied, either via command line arguments or from Windows Explorer's "open with" menu, opti will open to an empty window instead of displaying the file if the file's extension contains any uppercase letters.

For example, a file with this name will open as expected: `image.png`
These will not: `image.PNG`, `image.Png`

OS: Windows 10 Version 1903

**Comment by torcado194** [comment]
weird, thanks for catching this! seemed to be an issue with a deep mimetype dependency . fixed in 9ec0706ed03eae7e2fb9ea118e6e903f727ef6ce, will package new build after i fix the other issue 😊
